---
- name: Get Interface Details using ios_command
  hosts: iosxe
  gather_facts: no
  tasks:
    - name: Run 'show interfaces' command
      cisco.ios.ios_command:
        commands: 
          - show interfaces
      register: interfaces_output

    - name: Display the interface output
      debug:
        var: interfaces_output.stdout_lines

